imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    nodes:
        services:
            mysql: mysql
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

        tests-and-coverage:
            tests:
                before:
                    -
                        command: "mysql -u root --password="" < test/travis.sql"
                override:
                    -
                        command: "make phpunit"
                        coverage:
                            file: "build/coverage.clover"
                            format: "php-clover"