language: php

php:
    - "7.2"
    - "7.3"
    - hhvm
    - nightly

sudo: false

git:
    submodules: false

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm

# addons:
#     sonarcloud:
#         organization: "canax"

before_script:
    - make install

script:
    - make check
    - make test
    #- sonar-scanner

notifications:
    urls:
      - https://webhooks.gitter.im/e/d22ae4887d7128ff1092
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always